import {
  LucideArrowLeftRight,
  LucideBarChart3,
  LucideBell,
  LucideBuilding2,
  LucideChevronDown,
  LucideClock,
  LucideCreditCard,
  LucideFileCheck2,
  LucideFileText,
  LucideHandshake,
  LucideIdCard,
  LucideLandmark,
  LucideLayoutDashboard,
  LucideLogOut,
  LucideMenu,
  LucidePercent,
  LucidePiggyBank,
  LucidePlus,
  LucideRefreshCw,
  LucideSearch,
  LucideSettings,
  LucideTrendingUp,
  LucideUsers,
  LucideWallet,
} from '@lucide/angular';

/** Icons registered once for the whole app and looked up by kebab-case name via `[lucideIcon]`. */
export const APP_ICONS = [
  LucideArrowLeftRight,
  LucideBarChart3,
  LucideBell,
  LucideBuilding2,
  LucideChevronDown,
  LucideClock,
  LucideCreditCard,
  LucideFileCheck2,
  LucideFileText,
  LucideHandshake,
  LucideIdCard,
  LucideLandmark,
  LucideLayoutDashboard,
  LucideLogOut,
  LucideMenu,
  LucidePercent,
  LucidePiggyBank,
  LucidePlus,
  LucideRefreshCw,
  LucideSearch,
  LucideSettings,
  LucideTrendingUp,
  LucideUsers,
  LucideWallet,
];
